### ISSUE TITLE
Allow changing tokenizer state to PLAINTEXT

### ISSUE THREAD

**Issue by doublec** [servo/html5ever#109]
This came from mozilla/servo#4181. The spec for [dealing with text/plain](https://html.spec.whatwg.org/multipage/browsers.html#read-text) has:

> and switch the HTML parser's tokenizer to the PLAINTEXT state.

I'm doing this in doublec/servo@5d4e7efa by using `<plaintext>` as that seems to be the only way of changing to Plaintext.

Can an API be added to allow switching the state for this use case?

**Comment by kmcallister** [comment]
Sure, I'd be happy to review a PR for that. Maybe it can use the existing `query_state_change`.
