### ISSUE TITLE
Convert match_token to use rust-aster

### ISSUE THREAD

**Issue by kmcallister** [servo/html5ever#112]
Convert match_token to use [rust-aster](https://github.com/erickt/rust-aster) and possibly [rust-quasi](https://github.com/erickt/rust-quasi).

**Comment by kmcallister** [comment]
See #53.

**Comment by Ygg01** [comment]
Will this help with #53? rust-aster and rust-quasi are both on nightly branch at time of writing this.

**Comment by Ygg01** [comment]
@nox I think this is essentially closed with newest updates with quasi/syn.

**Comment by SimonSapin** [comment]
Yes, thanks.
