### ISSUE TITLE
Parse HTML integration points in MathML

### ISSUE THREAD

**Issue by kmcallister** [servo/html5ever#119]
This is annoying because you have to know [the original attributes that a node was created with](https://html.spec.whatwg.org/multipage/syntax.html#html-integration-point).

**Comment by nox** [comment]
Related tests:

* tb: tests20.dat-34
* tb: tests20.dat-35
* tb: tests20.dat-36
* tb: tests20.dat-37

**Comment by GuillaumeGomez** [comment]
I'll work on it (but will need help).

**Comment by nox** [comment]
This was done by @GuillaumeGomez.
