### ISSUE TITLE
Text node normalization is missing

### ISSUE THREAD

**Issue by jdm** [servo/html5ever#126]
The "html5 tokenizer" tests at html5test demonstrate that `e.innerHTML = "&lang;&rang;";` produces two text nodes in Servo, not one.

Relevant source at https://github.com/NielsLeenheer/html5test/blob/ce8268b2ec71ebdfa6fc6cefc989ba8e6ce544e5/scripts/6/engine.js#L412-L480 .

**Comment by kmcallister** [comment]
From the `TreeSink` trait:

```rust
/// Append a node as the last child of the given node.  If this would
/// produce adjacent sibling text nodes, it should concatenate the text
/// instead. [...]
fn append(&mut self, parent: Self::Handle, child: NodeOrText<Self::Handle>);
```

Based on which I'd say the bug is in Servo. As an incremental, streaming parser, there is nothing html5ever can/should do other than tell the client to combine text nodes.

**Comment by jdm** [comment]
Duly noted!
