### ISSUE TITLE
Panic when building

### ISSUE THREAD

**Issue by marvelm** [servo/html5ever#129]
I'm not sure if I should be creating an issue here or in the rust-lang repo.

Here's what I was trying to run:

```
extern crate html5ever;

use std::fs::File;
use std::io::{self, BufRead, BufReader, Read, Write};
use std::path::Path;
use std::default::Default;

use html5ever::sink::rcdom::RcDom;
use html5ever::{parse, one_input};

fn main() {
    let mut file = BufReader::new(File::open("aksdjasd").unwrap());
    let mut source = String::new();
    file.read_to_string(&mut source).unwrap();
    let dom: RcDom = parse(one_input(source.clone()), Default::default());
}
```

>
›+ rustc --version
rustc 1.1.0-nightly (c4b23aec4 2015-04-29) (built 2015-04-28)
a_@s-MacBook-Pro ~/dev/rivets ‹master! 77353e5a7 2d›
›+ cargo run --verbose
       Fresh libc v0.1.6
       Fresh httparse v0.1.1
       Fresh encoding_index_tests v0.1.4
       Fresh pkg-config v0.3.3
       Fresh typeable v0.1.1
       Fresh mac v0.0.2 (https://github.com/reem/rust-mac#6316d3f4)
       Fresh string_cache_shared v0.1.0 (https://github.com/servo/string-cache#c5912f92)
       Fresh unicase v0.1.0
       Fresh gcc v0.3.5
       Fresh smallvec v0.1.3
       Fresh traitobject v0.0.1
       Fresh modifier v0.1.0
       Fresh quicksort v1.0.0
       Fresh rustc-serialize v0.3.14
       Fresh mac v0.0.2
       Fresh debug-builders v0.1.0
       Fresh bitflags v0.1.1
       Fresh matches v0.1.2
       Fresh phf_shared v0.7.3
       Fresh lazy_static v0.1.10
       Fresh num_cpus v0.2.3
       Fresh log v0.3.1
       Fresh rand v0.3.8
       Fresh encoding-index-japanese v1.20141219.5
       Fresh encoding-index-simpchinese v1.20141219.5
       Fresh encoding-index-korean v1.20141219.5
       Fresh encoding-index-singlebyte v1.20141219.5
       Fresh encoding-index-tradchinese v1.20141219.5
       Fresh error v0.1.7
       Fresh unsafe-any v0.4.1
       Fresh conduit-mime-types v0.7.3
       Fresh html5ever_macros v0.0.0 (https://github.com/servo/html5ever.git#74dc5f5a)
       Fresh url v0.2.31
       Fresh phf v0.7.3
       Fresh string_cache_plugin v0.1.1 (https://github.com/servo/string-cache#c5912f92)
       Fresh mime v0.0.10
       Fresh phf_generator v0.7.3
       Fresh encoding v0.2.32
       Fresh typemap v0.3.0
       Fresh phf_macros v0.7.3
       Fresh cssparser v0.3.1
       Fresh openssl-sys v0.6.2
       Fresh time v0.1.25
       Fresh plugin v0.2.6
       Fresh string_cache v0.1.0 (https://github.com/servo/string-cache#c5912f92)
       Fresh openssl v0.6.2
       Fresh html5ever v0.0.0 (https://github.com/servo/html5ever.git#74dc5f5a)
       Fresh selectors v0.1.0 (https://github.com/servo/rust-selectors.git#1fda09bf)
       Fresh cookie v0.1.20
       Fresh hyper v0.3.15
   Compiling rivets v0.1.0 (file:///Users/a_/dev/rivets)
     Running `rustc src/main.rs --crate-name rivets --crate-type bin -g --out-dir /Users/a_/dev/rivets/target/debug --emit=dep-info,link -L dependency=/Users/a_/dev/rivets/target/debug -L dependency=/Users/a_/dev/rivets/target/debug/deps --extern time=/Users/a_/dev/rivets/target/debug/deps/libtime-e758cbe877e9589d.rlib --extern iron=/Users/a_/dev/rivets/target/debug/deps/libiron-74d92b575c467e01.rlib --extern selectors=/Users/a_/dev/rivets/target/debug/deps/libselectors-c06f32be3c0f6907.rlib --extern html5ever=/Users/a_/dev/rivets/target/debug/deps/libhtml5ever-6ea0d790b7d5e904.rlib -L native=/usr/lib -L native=/Users/a_/dev/rivets/target/debug/build/openssl-sys-5040130ff99796a0/out -L native=/Users/a_/dev/rivets/target/debug/build/time-e758cbe877e9589d/out`
       Fresh iron v0.1.16
src/main.rs:4:15: 4:19 warning: unused import, #[warn(unused_imports)] on by default
src/main.rs:4 use std::io::{self, BufRead, BufReader, Read, Write};
                            ^~~~
src/main.rs:4:21: 4:28 warning: unused import, #[warn(unused_imports)] on by default
src/main.rs:4 use std::io::{self, BufRead, BufReader, Read, Write};
                                  ^~~~~~~
src/main.rs:4:47: 4:52 warning: unused import, #[warn(unused_imports)] on by default
src/main.rs:4 use std::io::{self, BufRead, BufReader, Read, Write};
                                                            ^~~~~
src/main.rs:5:5: 5:20 warning: unused import, #[warn(unused_imports)] on by default
src/main.rs:5 use std::path::Path;
                  ^~~~~~~~~~~~~~~
src/main.rs:15:9: 15:12 warning: unused variable: `dom`, #[warn(unused_variables)] on by default
src/main.rs:15     let dom: RcDom = parse(one_input(source.clone()), Default::default());
                       ^~~
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: bpos.to_usize() >= mbc.pos.to_usize() + mbc.bytes', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/codemap.rs:777

>stack backtrace:
   1:        0x10ad1b24f - sys::backtrace::write::h0714aaf7fe41e02dzVr
   2:        0x10ad238c0 - panicking::on_panic::hb86b9b356f51f92dEVv
   3:        0x10acdfc35 - rt::unwind::begin_unwind_inner::h58f79e41dbedf2efnDv
   4:        0x10a401fcf - rt::unwind::begin_unwind::h16912456783326464005
   5:        0x10a48d20a - codemap::CodeMap::bytepos_to_file_charpos::hc1ce2cdd91243f32AAA
   6:        0x10a48b240 - codemap::CodeMap::lookup_char_pos::had549d847cafaf2b7qA
   7:        0x10766f139 - trans::debuginfo::set_source_location::he7e6b95e0509cb0cyZw
   8:        0x10765d8e7 - trans::expr::trans_into::hee612b3af8e4a25d08z
   9:        0x1075dc155 - trans::controlflow::trans_block::h3ba7e3f7cac3c7e4n6u
  10:        0x1075da9d6 - trans::base::trans_closure::hd2ebe43a70d93c1cIFh
  11:        0x1075dc7ae - trans::base::trans_fn::h2c79378d4e5f9c78qQh
  12:        0x107620628 - trans::monomorphize::monomorphic_fn::hbea364081d1869b6QLJ
  13:        0x10760feaf - trans::callee::trans_fn_ref_with_substs::h31d030e7dadb0630RHn
  14:        0x10760e6e2 - trans::callee::trans_fn_ref::he238302f6b47300fWvn
  15:        0x107624331 - trans::meth::trans_method_callee::h77e3affc0347e058WII
  16:        0x107622883 - trans::callee::trans_call_inner::h10485922579166683084
  17:        0x10768b96a - trans::expr::trans_rvalue_dps_unadjusted::h252239214ba28887F7A
  18:        0x107689c84 - trans::expr::trans_unadjusted::hef427853dc23df82cCA
  19:        0x1075ba89f - trans::expr::trans::h9269e8f70b3789c4jfA
  20:        0x10768eb97 - trans::expr::trans_rvalue_stmt_unadjusted::hb48c7764e747ade5U1A
  21:        0x10765dd44 - trans::expr::trans_into::hee612b3af8e4a25d08z
  22:        0x10765d6ec - trans::controlflow::trans_stmt_semi::h0063da44ed2f8f5br5u
  23:        0x1075dbe08 - trans::controlflow::trans_block::h3ba7e3f7cac3c7e4n6u
  24:        0x1075da9d6 - trans::base::trans_closure::hd2ebe43a70d93c1cIFh
  25:        0x1075dc7ae - trans::base::trans_fn::h2c79378d4e5f9c78qQh
  26:        0x107620628 - trans::monomorphize::monomorphic_fn::hbea364081d1869b6QLJ
  27:        0x10760feaf - trans::callee::trans_fn_ref_with_substs::h31d030e7dadb0630RHn
  28:        0x10760e6e2 - trans::callee::trans_fn_ref::he238302f6b47300fWvn
  29:        0x107624331 - trans::meth::trans_method_callee::h77e3affc0347e058WII
  30:        0x107622883 - trans::callee::trans_call_inner::h10485922579166683084
  31:        0x10768b96a - trans::expr::trans_rvalue_dps_unadjusted::h252239214ba28887F7A
  32:        0x10765dc07 - trans::expr::trans_into::hee612b3af8e4a25d08z
  33:        0x10765d6ec - trans::controlflow::trans_stmt_semi::h0063da44ed2f8f5br5u
  34:        0x1075dbe08 - trans::controlflow::trans_block::h3ba7e3f7cac3c7e4n6u
  35:        0x1075da9d6 - trans::base::trans_closure::hd2ebe43a70d93c1cIFh
  36:        0x1075dc7ae - trans::base::trans_fn::h2c79378d4e5f9c78qQh
  37:        0x10762007f - trans::monomorphize::monomorphic_fn::hbea364081d1869b6QLJ
  38:        0x10760feaf - trans::callee::trans_fn_ref_with_substs::h31d030e7dadb0630RHn
  39:        0x10760e6e2 - trans::callee::trans_fn_ref::he238302f6b47300fWvn
  40:        0x10760a1a5 - trans::callee::trans::h622673fde382071efln
  41:        0x107620e7d - trans::callee::trans_call_inner::h3083687813649051194
  42:        0x10768b7fd - trans::expr::trans_rvalue_dps_unadjusted::h252239214ba28887F7A
  43:        0x10765dc07 - trans::expr::trans_into::hee612b3af8e4a25d08z
  44:        0x1076df461 - trans::_match::mk_binding_alloca::h17959596099753258142
  45:        0x1075cb6a9 - trans::base::init_local::h3db8e9b7c000da1d3Yg
  46:        0x1075dbe33 - trans::controlflow::trans_block::h3ba7e3f7cac3c7e4n6u
  47:        0x1075da9d6 - trans::base::trans_closure::hd2ebe43a70d93c1cIFh
  48:        0x1075dc7ae - trans::base::trans_fn::h2c79378d4e5f9c78qQh
  49:        0x10762007f - trans::monomorphize::monomorphic_fn::hbea364081d1869b6QLJ
  50:        0x10760feaf - trans::callee::trans_fn_ref_with_substs::h31d030e7dadb0630RHn
  51:        0x10760e6e2 - trans::callee::trans_fn_ref::he238302f6b47300fWvn
  52:        0x10760a1a5 - trans::callee::trans::h622673fde382071efln
  53:        0x107620e7d - trans::callee::trans_call_inner::h3083687813649051194
  54:        0x10768b7fd - trans::expr::trans_rvalue_dps_unadjusted::h252239214ba28887F7A
  55:        0x10765dc07 - trans::expr::trans_into::hee612b3af8e4a25d08z
  56:        0x1076df461 - trans::_match::mk_binding_alloca::h17959596099753258142
  57:        0x1075cb6a9 - trans::base::init_local::h3db8e9b7c000da1d3Yg
  58:        0x1075dbe33 - trans::controlflow::trans_block::h3ba7e3f7cac3c7e4n6u
  59:        0x1075da9d6 - trans::base::trans_closure::hd2ebe43a70d93c1cIFh
  60:        0x1075dc7ae - trans::base::trans_fn::h2c79378d4e5f9c78qQh
  61:        0x1075dfb68 - trans::base::trans_item::h901d48520ee05543Cei
  62:        0x1075eeaaa - trans::base::trans_crate::hca38de41199d64b7p3i
  63:        0x107459dfe - driver::phase_4_translate_to_llvm::hd712c3b75a1dca10nOa
  64:        0x1074323a6 - driver::compile_input::h7c6cf9b085c57594Qba
  65:        0x1074f1ac3 - run_compiler::h55b523753cbd518765b
  66:        0x1074ef22a - boxed::F.FnBox<A>::call_box::h11476165885616507686
  67:        0x1074ee767 - rt::unwind::try::try_fn::h13518150216340287792
  68:        0x10ada5c58 - rust_try_inner
  69:        0x10ada5c45 - rust_try
  70:        0x1074eea4e - boxed::F.FnBox<A>::call_box::h735039165869315632
  71:        0x10ad222bd - sys::thread::Thread::new::thread_start::hf4c42a114072ab47mYu
  72:     0x7fff8fc23267 - _pthread_body
  73:     0x7fff8fc231e4 - _pthread_start

>Could not compile `rivets`.

>Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name rivets --crate-type bin -g --out-dir /Users/a_/dev/rivets/target/debug --emit=dep-info,link -L dependency=/Users/a_/dev/rivets/target/debug -L dependency=/Users/a_/dev/rivets/target/debug/deps --extern time=/Users/a_/dev/rivets/target/debug/deps/libtime-e758cbe877e9589d.rlib --extern iron=/Users/a_/dev/rivets/target/debug/deps/libiron-74d92b575c467e01.rlib --extern selectors=/Users/a_/dev/rivets/target/debug/deps/libselectors-c06f32be3c0f6907.rlib --extern html5ever=/Users/a_/dev/rivets/target/debug/deps/libhtml5ever-6ea0d790b7d5e904.rlib -L native=/usr/lib -L native=/Users/a_/dev/rivets/target/debug/build/openssl-sys-5040130ff99796a0/out -L native=/Users/a_/dev/rivets/target/debug/build/time-e758cbe877e9589d/out` (exit code: 101)

**Comment by Manishearth** [comment]
Looks like https://github.com/rust-lang/rust/issues/24687 to me , which was fixed (https://github.com/rust-lang/rust/pull/24932), but very recently so it might not be in the nightly yet.

**Comment by marvelm** [comment]
It's fixed in the latest nightly.
