### ISSUE TITLE
print-rcdom.rs example fails to compile when using html5ever as a library

### ISSUE THREAD

**Issue by Alex-Addy** [servo/html5ever#132]
When attempting to compile and run the [`examples/print-rcdom.rs`](https://github.com/servo/html5ever/blob/master/examples/print-rcdom.rs) from a fresh project with html5ever as a dependency it fails to compile.

The first error is when it fails to find the crate `string_cache` on line 17. Upon deleting this line and `#![plugin(string_cache_plugin)]` when it fails there as well, it then fails with an undefined macro error for `ns!` on lines 44 and 47. Upon deleting those lines it fails to find the crate `html5ever_dom_sink` on line 13. This is a blocking error as this crate is needed for the match that is the meat of the example. 

From looking the project a bit, it seems as if the examples were never tested outside of the project itself as these things are accessible from within the project, but not from without, which is the purpose of the example.

This was done with rustc version `rustc 1.1.0-nightly (c2b30b86d 2015-05-12) (built 2015-05-13)`.

**Comment by SimonSapin** [comment]
Examples are compiled as part of `cargo test`. The solution to not finding the `string_cache` crate is to add it as a dependency in your `Cargo.toml` file.

If you provide a full example I can help fixing it up.

**Comment by SimonSapin** [comment]
Closing as this doesn't seem to be an issue in html5ever.
