### ISSUE TITLE
Make html5ever available on crates.io

### ISSUE THREAD

**Issue by Wilfred** [servo/html5ever#133]
Currently, it's not possible to install html5ever from crates.io. It would be nice to fix that.

This will require explicit releases, although it might be tricky until Rust 1.1 since depending on string-cache requires supporting `#![feature(core, static_assert)]`.

**Comment by SimonSapin** [comment]
Publishing on crates.io is independent from (not) using unstable features (and running on Rust beta/stable).

**Comment by Manishearth** [comment]
(We also use `#![feature(plugins)]` transitively through PHF, so either way it's going to be a long time before we support stable)

But yes, crates  using unstable features can and should go on crates.io. It's a different question if we want to commit to the stability of h5e itself (I assume not for now), or stick to a 0.0.* series for now.

**Comment by SimonSapin** [comment]
Stability is also fairly independent of publication in the registry. Cargo extrapolates SemVer semantics into `0.x.y` versions, where x could be incremented for breaking changes and y for non-breaking.

The question is, @kmcallister, are you interested in making regular publications?

**Comment by Manishearth** [comment]
I thought 0.* versions in semver were allowed to all be breaking?

**Comment by Ygg01** [comment]
I think you are allowed to add interface but not a breaking change.

**Comment by SimonSapin** [comment]
semver.org says “Anything may change at any time.” about 0.x.y. But Cargo still assumes additional semantics and will automatically upgrade you e.g. to 0.3.5 but not to 0.4.0 if you specify `[dependencies] foo = "0.3.2"`.

**Comment by frewsxcv** [comment]
https://users.rust-lang.org/t/html5ever-is-on-crates-io/1818

This can probably be closed, right?

**Comment by SimonSapin** [comment]
Yes, thanks!
