### ISSUE TITLE
Test the C API

### ISSUE THREAD

**Issue by kostya** [servo/html5ever#143]
```
cd capi
cargo build --release
  Compiling lazy_static v0.1.10
   Compiling rustc-serialize v0.3.14
   Compiling mac v0.0.2 (https://github.com/reem/rust-mac#6316d3f4)
   Compiling gcc v0.3.5
   Compiling libc v0.1.8
   Compiling debug-builders v0.1.0
   Compiling string_cache_shared v0.1.0 (https://github.com/servo/string-cache#c5912f92)
   Compiling phf_shared v0.7.3
   Compiling mac v0.0.2
   Compiling rand v0.3.8
   Compiling log v0.3.1
   Compiling string_cache_plugin v0.1.1 (https://github.com/servo/string-cache#c5912f92)
   Compiling phf v0.7.3
   Compiling time v0.1.25
   Compiling phf_generator v0.7.3
   Compiling phf_macros v0.7.3
   Compiling html5ever_macros v0.0.0 (file:///Users/kostya/projects/html5ever/capi)
   Compiling string_cache v0.1.0 (https://github.com/servo/string-cache#c5912f92)
   Compiling html5ever v0.0.0 (file:///Users/kostya/projects/html5ever/capi)
   Compiling html5ever_capi v0.0.0 (file:///Users/kostya/projects/html5ever/capi)
note: link against the following native artifacts when linking against this static library
note: the order and any duplication can be significant on some platforms, and so may need to be preserved
note: library: c
note: library: m
note: library: System
note: library: pthread
note: library: c
note: library: m
```

```
ls target/release/lib*
target/release/libhtml5ever_capi.a
```

```
cd ../
cd examples/capi
gcc tokenize.c -I ../../capi/include/ -L ../../capi/target/release/ -lhtml5ever_capi -lc -lm -lSystem -lpthread
Undefined symbols for architecture x86_64:
  "_h5e_tokenizer_end", referenced from:
      _main in tokenize-BqDdVq.o
  "_h5e_tokenizer_feed", referenced from:
      _main in tokenize-BqDdVq.o
  "_h5e_tokenizer_free", referenced from:
      _main in tokenize-BqDdVq.o
  "_h5e_tokenizer_new", referenced from:
      _main in tokenize-BqDdVq.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by SimonSapin** [comment]
There is currently no tests for the C API, so it’s very plausible that it’s broken! We’ll need to fix this.

**Comment by Ygg01** [comment]
I've noticed that examples use [h5e_buf](https://github.com/servo/html5ever/blob/master/examples/capi/tokenize.c#L18), which was removed in favor of StrTendril. Only instance I ever found h5e_buf is [nrc/benchmarks repo](https://github.com/nrc/benchmarks/blob/0d05be706db6673c07a33820a01c6f2f00d6c0ff/html5ever-2015-05-15/capi/src/lib.rs#L23 ). Perhaps that's the issue here?

**Comment by SimonSapin** [comment]
Ah, I missed that example file when landing the conversion to Tendril: https://github.com/servo/html5ever/pull/142. But I don’t see a Makefile or build script for it. Yes, it still needs to be updated for Tendril. And `scripts/travis-build.sh` should build and run it, testing the output. `h5e_buf` was defined here:

https://github.com/servo/html5ever/blob/3302cb5b0988cca873a379f85eaff97fd8d6533f/capi/include/html5ever.h
https://github.com/servo/html5ever/blob/3302cb5b0988cca873a379f85eaff97fd8d6533f/capi/src/lib.rs

**Comment by Ygg01** [comment]
Well, html5ever now uses string cache, so you'll probably need to land the capi for String cache first :(

**Comment by SimonSapin** [comment]
We removed the C API in #204 since it had been broken for a long time and no-one was maintaining it. If something related is to be added again, I’d rather see it evolve for a while outside this repository.
