### ISSUE TITLE
RcDom links are all broken

### ISSUE THREAD

**Issue by chris-morgan** [servo/html5ever#148]
Loads of things refer to `RcDom` and `examples/print-rcdom.rs`. All the links are broken, as it’s moved to the `html5ever_dom_sink` crate (not included in the [generated docs](http://kmcallister.github.io/docs/html5ever/html5ever/)) and the `dom_sink` subdirectory of the repository.

**Comment by SimonSapin** [comment]
rustdoc, y u no xref :(
