### ISSUE TITLE
Move parser suspension code from Servo into h5e proper

### ISSUE THREAD

**Issue by Ms2ger** [servo/html5ever#198]
One issue this split has caused is documented in https://github.com/servo/servo/pull/9677

**Comment by SimonSapin** [comment]
What does this mean more precisely? Do you have a new design in mind?

**Comment by jdm** [comment]
There is currently one way to interrupt parsing, via the script element callback. There's no way to queue up bytes for future parsing without continuing to the process, which would be a useful addition. Similarly, this could make it clearer how to implement the insertion point that's necessary for document.write.

**Comment by nox** [comment]
This is no longer relevant because I moved even more stuff to Servo to support document.write. Adding stuff in h5e wasn't the solution.
