### ISSUE TITLE
Bad parsing with no closing tag?

### ISSUE THREAD

**Issue by LeMoussel** [servo/html5ever#211]
I'm not entirely sure if this is a bug, but when tested [print-rcdom.rs](https://github.com/servo/html5ever/blob/master/examples/print-rcdom.rs) on this page http://cocon.se/, give this result

> 
>                     <div class="col-md-6 copyright">
>                         <ul class="social">
>                             <li>
>                                 <a target="_blank" href="http://twitter.com/SylvainDeaure">
>                                     <i class="fa fa-twitter">
>                         #text: (c) 2016 Cocon.Se
>                         <div class="zerif-copyright-box" id="mentions">
>                             <a class="zerif-copyright" href="/mentions/">
>                                 #text: Mentions l\u{e9}gales
>                         <a class="zerif-copyright" href="/mentions/">
>                             #text: \n
>                     <a class="zerif-copyright" href="/mentions/">
>                         #text:
>                         
>                         #text: \n\n
>             <a class="zerif-copyright" href="/mentions/">
>                 #text:
>                 
>                 #text: \n\n\n\n
>                 <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js?ver=1.11.3">
>                 #text: \n
>                 <script type="text/javascript">
>                     #text: \n/* <![CDATA[ */\nvar post_notif_widget_ajax_obj = {\"ajax_url\":\"http:\\/\\/cocon.se\\/wp-admin\\/admin-ajax.php\",\"nonce\":\"fbaa1fb825\",\"processing_msg\":\"Processing...\"};\n/* ]]> */\n
>                 #text: \n
>                 <script type="text/javascript" src="http://cocon.se/wp-content/plugins/bwp-minify/cache/minify-b1-site-93169d5099459d3cd214c09375108af7.js?ver=1466496162">
>                 #text: \n\n\n\n\n\n\n\n\n\n\n
>     
>     
>     

With this errors
> Parse errors:
    Bad character
    Attributes on an end tag
    Found special tag while closing generic tag
    Unexpected open element
    Unexpected open element
    Unexpected open element
    Unexpected open tag at end of body

As you can see, there are four `href="/mentions/"`. Last three `href="/mentions/"`` are incorrect. There is only one link /mentions/ with text "Mentions légales" on HTML page.

This seems wrong to be due as the last `<a>`  tag is not closed (Firefox showing with red color) => `<a class="zerif-copyright" href="/mentions/">Mentions légales</a</div></div>`

**Comment by Ms2ger** [comment]
I expect this is correct per spec; elements such as `a` get cloned in cases like this. Feel free to reopen if you find we don't match the spec or other browsers here.
