### ISSUE TITLE
Missing states in tokenizer

### ISSUE THREAD

**Issue by Ygg01** [servo/html5ever#214]
Tokenizer [states.rs](https://github.com/servo/html5ever/blob/5293725a434bcd6edde1474f55d60a08617c03e3/src/tokenizer/states.rs) seems to be missing following states:
- [Comment Less than Sign State](https://html.spec.whatwg.org/multipage/syntax.html#comment-less-than-sign-state)
- [Comment Less than Sign Bang State](https://html.spec.whatwg.org/multipage/syntax.html#comment-less-than-sign-bang-state)
- [Comment Less than Sign Bang Dash State](https://html.spec.whatwg.org/multipage/syntax.html#comment-less-than-sign-bang-dash-state)
- [Comment Less than Sign Bang Dash Dash State](https://html.spec.whatwg.org/multipage/syntax.html#comment-less-than-sign-bang-dash-dash-state)

And their corresponding transitions in `src/tokenizer/mod.rs`.

**Comment by SimonSapin** [comment]
Do you have an example of input that is tokenized incorrectly as a result? Thanks!

**Comment by Ms2ger** [comment]
Added in https://github.com/whatwg/html/pull/1356

**Comment by SimonSapin** [comment]
I don’t see corresponding commits in https://github.com/html5lib/html5lib-tests/ , we should contribute some tests. https://github.com/whatwg/html/pull/1356#issuecomment-222793570 lists some interesting inputs.

**Comment by nox** [comment]
@SimonSapin I don't think these new states change anything except whether parse errors are reported.
