### ISSUE TITLE
Add Atom local_name "allowfullscreen"

### ISSUE THREAD

**Issue by farodin91** [servo/html5ever#234]

**Comment by SimonSapin** [comment]
Hi! Feel free to send a pull request that adds it to `atoms/local_names.txt` (preferably in its lexicographic order position) and increments the version number in `atoms/Cargo.toml` to 0.1.2.

**Comment by jackinloadup** [comment]
On it

**Comment by jackinloadup** [comment]
HA! looks like I was too late. Good to note the issue was that easy. I saw it last night but seems almost too straight forward.
