### ISSUE TITLE
html and xml named entity tables should be shared

### ISSUE THREAD

**Issue by froydnj** [servo/html5ever#261]
Right now, we have `data/entities.json` and `xml5ever/data/entities.json`, which are identical.  If a project (such as Servo) requires both `html5ever` and `xml5ever`, it'll have duplicate copies of the named entity tables, which are not particularly small--about 230K on x86-64 Linux, roughly half that on 32-bit platforms.

Sticking the entities and the process to generate a phf table for them in a separate, shared crate would alleviate this problem.  There might be issues down the road if sets of entities in HTML and XML are no longer identical...but I'm sure solutions can be worked out there if necessary.

**Comment by SimonSapin** [comment]
Yes, after discussion in https://github.com/Ygg01/xml5ever/issues/30 we’ve moved the xml5ever code into this repository. The followup that remains to do is sharing more code between them. Maybe the `html5ever_atoms` crate should be renamed something like `markup5ever` and be the place for all the shared stuff.

That’s the plan, it just has seemed low-priority so far.

**Comment by Ygg01** [comment]
>  There might be issues down the road if sets of entities in HTML and XML are no longer identical...but I'm sure solutions can be worked out there if necessary.

I don't think that should ever happen. XML5 is explicitly made to be close to HTML5 as possible.
