### ISSUE TITLE
Customising RcDom's Node?

### ISSUE THREAD

**Issue by jugglerchris** [servo/html5ever#265]
Hi,
I've been using html5ever with `RcDom`, which is mostly good enough for [what I'm doing](https://crates.io/crates/html2text).  However it'd be really useful if I could attach some extra data to each node (like cached size estimates when rendering tables to text in my case).

I think my needs would be served nicely by making it something like `RcDom<T:Default=()>`, where the `T` is used as an extra field in `Node` (and implements `Default` so that it can be filled in easily); I could then make an `RcDom<RefCell<usize>>` or similar.  Is this a change that would be considered (e.g. if a PR arrived along those lines)?

I'm sort of expecting the answer to be that `RcDom` is only an example and that I should roll my own (which I can do, though I'd probably want to copy it as a starting point).  I've also considered a hash map keyed on the `Node` addresses to keep the extra data in a separate data structure rather than modifying the DOM tree.  I'm open to any other suggestions!

Thanks,

Chris

**Comment by SimonSapin** [comment]
> I'm sort of expecting the answer to be that RcDom is only an example

Mostly so that html5ever can run its own tests, but it also works as an example yes.

> and that I should roll my own (which I can do, though I'd probably want to copy it as a starting point). 

Yes, I was going to suggest this. You can also look at https://github.com/SimonSapin/kuchiki (which is intended to be more user-friendly, with convenience methods etc.) although it also doesn’t support attaching custom data to nodes.

> I could then make an RcDom<RefCell<usize>> or similar.

`usize` is `Copy`, so `Cell` might be more convenient than `RefCell`.

**Comment by jugglerchris** [comment]
> You can also look at https://github.com/SimonSapin/kuchiki (which is intended to be more user-friendly, with convenience methods etc.) although it also doesn’t support attaching custom data to nodes.

Thanks, I'll look into kuchiki!  I guess in theory I could add always add custom attributes (with some care...)

> usize is Copy, so Cell might be more convenient than RefCell.

Thanks, good point - I was thinking `Cell` but wrote `RefCell`.
