### ISSUE TITLE
Consider making BufferQueue Send

### ISSUE THREAD

**Issue by cynicaldevil** [servo/html5ever#282]
This is needed for the Off-main thread HTML parsing project, where the tokenizer will operate in a separate thread, and the BufferQueue needs to be shared between threads. We can go about two separate ways to do this:
1. Refactor `BufferQueue`'s buffer field to contain `VecDeque<Tendril<UTF8, Atomic>>` instead of `VecDeque<StrTendril>`. This would mean that atomic Tendrils would be used everywhere, even where they're not needed.
2. Make `BufferQueue` generic. This would require a lot of refactoring, primarily in turning the structs and functions which rely on BufferQueue generic as well. `StrTendril` has been used heavily too, but changing that would be trivial.

cc @nox @SimonSapin

**Comment by SimonSapin** [comment]
Random ideas:

Do you want to send entire queues rather than individual tendrils? Could Servo’s other threads use `VecDeque<Tendril<UTF8, Atomic>>` directly?

**Comment by cynicaldevil** [comment]
I didn't understand your idea completely, but right now sending the entire queue is the plan.

**Comment by cynicaldevil** [comment]
Found another way to make it work, hence closing this.
