### ISSUE TITLE
Rust issue tracking

### ISSUE THREAD

**Issue by kmcallister** [servo/html5ever#30]
rust-lang/rust#15609: Autoderef chooses deref() when deref_mut() is needed for ref mut pattern
rust-lang/rust#16617: Syntactic context discarded when quoting a macro invocation
rust-lang/rust#18043: Bencher::iter should support per-iteration setup

**Comment by Ygg01** [comment]
Could we close this issue? 

Only rust-lang/rust#15609 is open, and I don't think we really used Bencher all that much?

**Comment by SimonSapin** [comment]
Agreed.
