### ISSUE TITLE
Remove `same_tree` and `has_parent_node` methods from the TreeSink trait

### ISSUE THREAD

**Issue by cynicaldevil** [servo/html5ever#303]
These methods are no longer used by the TreeBuilder and can be removed safely.

**Comment by rozuur** [comment]
Can I work on this?

**Comment by jdm** [comment]
@rozuur Sure!

**Comment by cynicaldevil** [comment]
@rozuur Any updates?

**Comment by rozuur** [comment]
@cynicaldevil  I will send a pull request by EOW.

**Comment by rozuur** [comment]
Made changes and all tests are passing.
