### ISSUE TITLE
Fix warnings in xml5ever

### ISSUE THREAD

**Issue by jdm** [servo/html5ever#315]
```
warning: unused macro definition
   --> target/package/xml5ever-0.11.0/src/tokenizer/mod.rs:609:1
    |
609 | / macro_rules! go_match ( ( $me:ident : $x:expr, $($pats:pat),+ => $($cmds:tt)* ) => (
610 | |     match $x {
611 | |         $($pats)|+ => go!($me: $($cmds)*),
612 | |         _ => (),
613 | |     }
614 | | ));
    | |___^
    |
    = note: #[warn(unused_macros)] on by default

warning: unused macro definition
   --> target/package/xml5ever-0.11.0/src/tokenizer/mod.rs:622:1
    |
622 | / macro_rules! peek ( ($me:expr) => (
623 | |     unwrap_or_return!($me.peek(), false)
624 | | ));
    | |___^

warning: variable does not need to be mutable
   --> target/package/xml5ever-0.11.0/src/tree_builder/mod.rs:359:13
    |
359 |         for mut attr in tag.attrs.iter_mut()
    |             ---^^^^^
    |             |
    |             help: remove this `mut`
    |
    = note: #[warn(unused_mut)] on by default
```

**Comment by milindjain0** [comment]
I would like to work on this. I am new to this and help from a mentor for getting started would be appreciated.

Thanks

**Comment by SimonSapin** [comment]
Hi @milindjain0. Are you familiar with GitHub’s pull request workflow?

After cloning this repository, you can run `cargo build` to compile everything. You should see the same warnings as above. Then change the code until you can compile without warnings, and send a pull request.

For the unused macros, double check that they don’t have a `#[macro_export]` attribute above them. This would make them available to users outside the crate, in which case we wouldn’t want to remove them. But I think the warning wouldn’t be shown in that case. You should be able to remove these two macros and have everything still compile.

As to the variable that doesn’t need to be mutable, the warning itself suggests a fix: removing `mut` in `for mut attr in tag.attrs.iter_mut()`.

Feel free to ask any question here on on the `#servo` channel on Mozilla IRC.

**Comment by milindjain0** [comment]
Hi,

I was able to build the code using ./mach build -d and run using ./mach run ...

I am not able to use cargo

Do I need to set environment variables for using Cargo?

Thanks

**Comment by KiChjang** [comment]
@milindjain0 You shouldn't be using mach for this issue, let alone this repository. What you need to do is clone html5ever, cd into it and run `cargo build` as @SimonSapin has outlined above.

**Comment by milindjain0** [comment]
@KiChjang I cloned html5ever and tried cargo -build but I am getting no command find I have not installed rust and cargo currently How do I know the version which needs to be installed?

Thanks

**Comment by jdm** [comment]
@milindjain0 Servo's build system installs a very specific version of rust in a particular place. I recommend following the regular Rust installation steps at https://www.rust-lang.org/en-US/install.html.

**Comment by milindjain0** [comment]
I am getting the following error on running `cargo build` 
```
Compiling void v1.0.2
   Compiling rustc-serialize v0.3.24
   Compiling unicode-xid v0.0.4
   Compiling string_cache_shared v0.3.0
error[E0463]: can't find crate for `core`

error: aborting due to previous error

error: Could not compile `void`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

error: Could not compile `string_cache_shared`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `core`

error: aborting due to previous error

error: Could not compile `unicode-xid`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

error: Could not compile `rustc-serialize`.

To learn more, run the command again with --verbose.
```

**Comment by milindjain0** [comment]
@jdm @KiChjang  @SimonSapin  Thanks Everything is working fine now!

**Comment by duxum** [comment]
Was playing with this and I did as @SimonSapin wrote, and there are no longer warnings. Should I go ahead and PR.
Thanks,

**Comment by duxum** [comment]
Was playing with this and did as @SimonSapin wrote, and there are no longer warnings. Should I go ahead PR.
Thanks,

**Comment by KiChjang** [comment]
@duxum Sorry, but isn't @milindjain0 already working on this issue?

**Comment by duxum** [comment]
@KiChjang Okay, no problem. However, I guess a tag that it is assigned should be added.

**Comment by milindjain0** [comment]
@KiChjang  @SimonSapin  @jdm I have made a PR after making the changes to remove the warning and `cargo build` is working

**Comment by milindjain0** [comment]
@jdm @KiChjang  @SimonSapin Can you suggest some other issue to work on or some feature?
