### ISSUE TITLE
xml5ever/CHANGELOG.md is broken and outdated

### ISSUE THREAD

**Issue by RazrFalcon** [servo/html5ever#321]
1. There are no links, so `[version]` is useless.
1. It's pretty outdated.

Should be updated or removed.

**Comment by Ygg01** [comment]
Hi RazrFalcon, yeah, I tried keeping changelog while I was working on it, but then it got integrated into the larger h5e repo.

The question is, whether h5e/m5e/x5e want to keep the Changelog. Is this useful for the project at large?

**Comment by jdm** [comment]
We don't use changelogs in other projects, so I am inclined to remove it.
