### ISSUE TITLE
[Question] Parsing HTML fragments

### ISSUE THREAD

**Issue by lnicola** [servo/html5ever#323]
Is there a way to parse some text as a `Text` node without a `body` element being automatically created?

See https://play.rust-lang.org/?gist=5632132a9b670f3831a10c931f78c28c&version=stable for an example. I'm interested in a way to have `<html>foo</html>` and `foo` parse differently.

**Comment by Ygg01** [comment]
Hi, the thing `parse_fragments` does is execute this algorithm:  https://html.spec.whatwg.org/multipage/parsing.html#parsing-html-fragments if you look at step 1, it's construct an html node.

What you guys needs is something else, I think. Would writing a custom TokenSink, that upon detecting a non-text token would just short circuits, work for you?
