### ISSUE TITLE
Write C bindings for the tree builder

### ISSUE THREAD

**Issue by kmcallister** [servo/html5ever#33]

**Comment by kmcallister** [comment]
The `TreeSink` API is generic over a `Handle` to a node.  In the C API this should be a wrapper around `void *`, which calls optional incref and decref callbacks on `Clone` and `Drop` respectively.

See [hubbub's tree builder API](https://github.com/servo/libhubbub/blob/master/docs/Treebuilder) as well.

**Comment by kmcallister** [comment]
Maybe expose the existing GC trace hooks to C code, as well?  It's potentially useful for writing bindings to a GC'd language.

**Comment by SimonSapin** [comment]
We removed the C API in #204 since it had been broken for a long time and no-one was maintaining it. If something related is to be added again, I’d rather see it evolve for a while outside this repository.
