### ISSUE TITLE
[Question] Remove formatting from HTML document when parsing?

### ISSUE THREAD

**Issue by Adonai** [servo/html5ever#340]
Hi, is it possible to remove HTML formatting (indentation, newlines) when parsing to DOM model?
I mean, like regexing out all "^\s+" and then ">/n<" except `<pre>` tags.

**Comment by SimonSapin** [comment]
html5ever itself doesn’t do that, whitespace between tags is considered no different from other text. What you could do is parse normally into a tree, and then traverse text nodes and do string manipulation.

**Comment by Adonai** [comment]
Ok, this answers my question so I'm closing it, thanks.

Regarding the suggestion, could please elaborate a bit, how would this be done? Suppose I have following html:
```html
fn test_list2() {
    let md = parse(r#"
    <p>
        <ul>
            <li>Seven things has lady Lackless
                <ul>
                    <li>Kingkiller</li>
                    <li>Chronicles</li>
                    <li>Series</li>
                </ul>
            </li>
            <li>Keeps them underneath her black dress</li>
            <li>One a thing that's not for wearing</li>
        </ul>
        <pre>
              code_part;
        </pre>
    </p>"#);
}
```

What text node manipulation (`NodeData::Text { ref content }`, I suppose?) would convert it to
```html
<p><ul><li>Seven things has lady Lackless<ul><li>Kingkiller</li><li>Chronicles</li><li>Series</li></ul></li><li>Keeps them underneath her black dress</li><li>One a thing that's not for wearing</li></ul></p><pre>
              code_part;
        </pre>
```
