### ISSUE TITLE
What is the inverse of `parse_document`?

### ISSUE THREAD

**Issue by murtyjones** [servo/html5ever#376]
Usage question:

I parsed an HTML document using `html5ever::driver::parse_document`, and added an attribute to a node. Now I'd like to convert the parsed document back to a `String`, but I'm not clear on how best to do this without doing something like [walking and printing the entire DOM](https://github.com/servo/html5ever/blob/master/html5ever/examples/print-rcdom.rs). Is there a method available to do the inverse of `parse_document`? Essentially convert an `RcDom` to a `String`?

**Comment by jdm** [comment]
You're looking for the [serialize](https://docs.rs/html5ever/0.23.0/html5ever/serialize/fn.serialize.html) API.

**Comment by murtyjones** [comment]
Nice, thanks!

For those in the same boat, here's some example usage where I write my parsed doc to a file:

```rust
    fn write_file_contents(&mut self, path: &String) {
        let doc: &Rc<Node> = &self.get_doc();
        let buffer = std::fs::File::create(path).expect("Could't create file.");
        html5ever::serialize::serialize(
            buffer,
            doc,
            html5ever::serialize::SerializeOpts::default(),
        )
        .expect("Couldn't write to file.");
    }
```
