### ISSUE TITLE
Unable to get parent element from Node

### ISSUE THREAD

**Issue by murtyjones** [servo/html5ever#377]
## Expected Behavior
Get the parent (`Option<Weak<Node>>`) from a Node using Cell's [`get`](https://doc.rust-lang.org/std/cell/struct.Cell.html#method.get)  method.

## Actual Behavior
```rust
error[E0599]: no method named `get` found for type `std::cell::Cell<std::option::Option<std::rc::Weak<html5ever::rcdom::Node>>>` in the current scope
  --> src/main.rs:27:34
   |
27 |     let parent = div_elem.parent.get();
   |                                  ^^^ help: did you mean: `set`
   |
   = note: the method `get` exists but the following trait bounds were not satisfied:
           `std::option::Option<std::rc::Weak<html5ever::rcdom::Node>> : std::marker::Copy`

error: aborting due to previous error
```

I can use another method, such as [`take`](https://doc.rust-lang.org/std/cell/struct.Cell.html#method.take), but would prefer not to remove the value from the Dom as I need to reuse it later on. Is there another way to get the parent out of the `Cell` wrapper?

**Comment by jdm** [comment]
I think you're looking for the `get` method.

**Comment by jdm** [comment]
Huh. This is a regression from https://github.com/servo/html5ever/commit/8bf65ef61daf612a3b4d7e6007fde7297d6210eb

**Comment by murtyjones** [comment]
For anyone like me who's trying to work around this, you may be able to use `.take()` + `.set()` + `.clone()` to effectively emulate `.get()`. E.g.:
```rust
let parent = target.parent.take();
target.parent.set(parent.clone());
```

**Comment by murtyjones** [comment]
The code I suggested above compiles but still yields a dangling weak pointer at runtime... anyone know of an alternative?

**Comment by jdm** [comment]
I'm looked into this, and the only solution I see is to make the parent field a RefCell instead of Cell. Node is going to continue to require a Drop implementation for the forseeable future, and this will prevent it being used with Cell methods that require a Copy bound.

**Comment by jdm** [comment]
Oh, I think I was wrong - I assumed this was a change in behaviour from earlier versions of html5ever, but `Cell<Rc<T>>` will never allow the use of `.get()`. I agree that this isn't particularly idiomatic, but I'm going to defer implementing the RefCell solution for now given that the take+set combo works.

**Comment by murtyjones** [comment]
@jdm Makes sense to me. `.take()` + `.set()` is working pretty well for my purposes and since it sounds like it's sticking around I'll close this out for now.
