### ISSUE TITLE
Replace rustc-serialize dev-dependency with serde_json

### ISSUE THREAD

**Issue by est31** [servo/html5ever#378]
serde 1.0 has been around [since over two years](https://github.com/serde-rs/serde/releases/tag/v1.0.0) now, so I think one could think about removing rustc-serialize. I see two tasks:

- [x] removal in html5ever tests: #379
- [x] removal in xml5ever tests: #382

**Comment by jdm** [comment]
* https://github.com/servo/html5ever/blob/284953ee8721e3442bb130c96e2428c2e8319274/xml5ever/Cargo.toml#L29
* https://github.com/servo/html5ever/blob/284953ee8721e3442bb130c96e2428c2e8319274/html5ever/Cargo.toml#L35

Example use:
* https://github.com/servo/html5ever/blob/284953ee8721e3442bb130c96e2428c2e8319274/xml5ever/tests/tokenizer.rs#L159-L206
* https://github.com/servo/html5ever/blob/284953ee8721e3442bb130c96e2428c2e8319274/xml5ever/tests/tokenizer.rs#L363

**Comment by est31** [comment]
Both PRs are merged, closing.
