### ISSUE TITLE
Drop of RcDom unexpectedly empties all Nodes

### ISSUE THREAD

**Issue by kornelski** [servo/html5ever#383]
This is a regression in 0.23 from 0.22. Previously, `Node` was independent from `RcDom` and it was possible to continue using `Node`s after dropping the `RcDom` object.

Since 0.23 dropping of `RcDom` clears document's `.children` as a side effect, making it impossible to use the document without keeping `RcDom` instance around. 

```rust
#[macro_use]
extern crate html5ever;
use html5ever::driver::*;
use markup5ever::tendril::TendrilSink;
use html5ever::rcdom::{RcDom};
use html5ever::QualName;

#[test]
fn clone_works() {
    let parser = parse_fragment(RcDom::default(), ParseOpts::default(), QualName::new(None, ns!(html), local_name!("div")), vec![]);
    let dom = parser.one("<body>");
    let doc = dom.document.clone();
    assert_eq!(1, doc.children.borrow().len(), "before drop");
    drop(dom);
    assert_eq!(1, doc.children.borrow().len(), "after drop");
}
```

with 

```toml
[dependencies]
html5ever = "0.22"
markup5ever = "0.8.1"
```

the test passes, and with

```toml
[dependencies]
html5ever = "0.23.0"
markup5ever = "0.8.1"
```

the test fails.

This dropping-of-nodes-at-distance is quite inconvenient. I used to be able to parse document fragments and return `Node` to their body. Now I'd have to return `(RcDom, Node)` everywhere to ensure their DOM lives.

**Comment by jdm** [comment]
Agreed. I've figured out a better solution to 8bf65ef61daf612a3b4d7e6007fde7297d6210eb that will avoid this behaviour.
