### ISSUE TITLE
Clarify docs for expanded_name!()

### ISSUE THREAD

**Issue by federicomenaquintero** [servo/html5ever#400]
I'm not sure if this is a typo in the macro pattern or just docs that could be improved :)  The `expanded_name!` macro can be used like `expanded_name!("", "foo")` for names without a namespace, or `expanded_name!(svg "bar")` for names with a namespace, in particular those that the `ns!` macro recognizes.

It took me a while to see why `expanded_name!(svg, "bar")` didn't compile - the macro definition does not have the comma in there.

The example in the docs just refers to the un-namespaced case.  My question is, is the lack of comma intentional?  Either way, I can update the docs.

**Comment by jdm** [comment]
There are many uses of expanded_name with a namespace in the code, so let's go ahead and update the docs.

**Comment by federicomenaquintero** [comment]
Thanks!  Posted a PR.
