### ISSUE TITLE
[Question] Stop the TreeBuilder or Tokenizer from processing the rest of the HTML after some data was found

### ISSUE THREAD

**Issue by glyphpoch** [servo/html5ever#426]
Hello,

I've been looking at the html5ever docs and it doesn't look like there's a way to stop the `TreeBuilder` or the `Tokenizer` from processing input HTML after we've found some data we were looking for, but I just wanted to confirm that this is actually the case...

Let's say we only want to get the `charset` attribute out of the HTML, which would normally be found at the beginning of the HTML document, here's a code example:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=42615c329cb939808b03c946fb754b5b

We look for the `charset` in `TreeSink`'s `create_element` implementation. If it's found then we could theoretically stop parsing at that point. Is there anything that can be called to interrupt the parser from doing any further work?

`NextParserState` enum looked promising at a first glance but it seems to have a different purpose in the parser.

**Comment by Ygg01** [comment]
Yeah. Not having a set state is an optimization. No ifs on every call means less branching. And that's something you want in a performant parser. I think you could spin treesink in another thread and just kill it if you find what you want.

**Comment by glyphpoch** [comment]
Okay, yeah makes sense, thanks for confirming it. Might just do some preprocessing and parse relevant fragments...
