### ISSUE TITLE
Implement the "XML5" syntax

### ISSUE THREAD

**Issue by kmcallister** [servo/html5ever#43]
A parser for well-formed XML 1.0 is a very different beast from a HTML parser.  But there's this [XML5](https://code.google.com/p/xml5/) spec that is quite similar to HTML parsing and could re-use a lot of the machinery, if not the actual parse rules.  Servo could potentially use this for all XML parts of the Web platform. See servo/servo#3319.

**Comment by SimonSapin** [comment]
Started in https://github.com/Ygg01/xml5ever
