### ISSUE TITLE
markup5ever version outdated

### ISSUE THREAD

**Issue by jclds139** [servo/html5ever#435]
m5e 0.10.0 doesn't build on some aarch64 and arm7h devices (like Raspberry Pis, see Morganamilo/paru#258)

It looks like 3afd8d63853627e530b3063b0185eea3732cc29f fixes the problem because the error comes from serde_json failing to read the entities file, but there hasn't been a new version since then. Can we get a new release so these changes can be pulled in?

**Comment by Ygg01** [comment]
Yeah, this seems like an issue worth addressing. The PR should be dead simple, just update version number.

**Comment by Ygg01** [comment]
@jdm did we publish a new version of markup5ever? This seems like easy fix.

**Comment by jdm** [comment]
I'll do it in #438.
