### ISSUE TITLE
Benchmark the C API

### ISSUE THREAD

**Issue by kmcallister** [servo/html5ever#44]
Quantify the overhead of the extra indirection, the virtual calls, etc.

**Comment by SimonSapin** [comment]
We removed the C API in #204 since it had been broken for a long time and no-one was maintaining it. If something related is to be added again, I’d rather see it evolve for a while outside this repository.

**Comment by SimonSapin** [comment]
I have some benchmarks in https://github.com/SimonSapin/html5ever-python/tree/master/benchmarks , but they also include the overhead of Python’s CFFI and of creating Python objects for the tree.
