### ISSUE TITLE
UnsupportedPseudoClassOrElement("has")

### ISSUE THREAD

**Issue by Antiarchitect** [servo/html5ever#441]
I'm trying to parse (relatively) simple html and want to use:
```
let selector = Selector::parse("h1,h4:has(+p),h4 + p").unwrap();
```
gives:
```
UnsupportedPseudoClassOrElement("has")
```
The idea is to parse all `h1` tags but only `h4` and `p` going together.

P.S.
```
Selector::parse("h1,h4:not(h4 + p):not(h4 + p),h4 + p").unwrap();
```
not works either with
```
UnexpectedToken(Delim('+'))
```

I use scraper crate which is based on html5ever.
It may be there is another way to do this, but I do not how to write a proper CSS selector correctly.

**Comment by jdm** [comment]
scraper is based on html5ever and the selectors crate, which is where the actual CSS selector matching is implemented. That crate is part of Servo in https://github.com/servo/servo/tree/master/components/selectors. However, there is an open issue to implement the `has` pseudo-class at https://github.com/servo/servo/issues/25133.

**Comment by Antiarchitect** [comment]
@jdm Thank you so much for the hint!
