### ISSUE TITLE
Yank xml5ever 0.16.0 and html5ever 0.25.0

### ISSUE THREAD

**Issue by xfix** [servo/html5ever#463]
Due to #402, those versions doesn't build with newest Rust. Doing so would help with `cargo update -Z minimal-versions` builds (https://github.com/rust-lang/cargo/issues/5657).

**Comment by untitaker** [comment]
Can you elaborate on what the actual issue is that makes that particular version not compile on latest Rust, and what yanking would accomplish to drive the Cargo issue forward?

**Comment by xfix** [comment]
The issue is that those versions used a glob import for `matches` macro, and this broke when standard library introduced `matches` macro in prelude - Rust compiler refused to use either of those due to conflict. c7691e9577615d37f6f5cbfdc2a803c570997bbd fixed the issue.

For all intents and purposes those versions are broken, nobody downloads them anyway, and having them be yanked would help when using `cargo update -Z minimal-versions` with dependencies that depend on those versions of crates. Nobody downloads those particular versions anyway according to lib.rs:

xml5ever 0.16.2 has 30K downloads per month
xml5ever 0.16.1 has 29K downloads per month
xml5ever 0.16.0 has 40 downloads per month

html5ever 0.25.1 has 105K downloads per month
html5ever 0.25.0 has 56 downloads per month

**Comment by untitaker** [comment]
I posted my concerns with this approach here: https://github.com/rust-lang/cargo/issues/5657#issuecomment-1018846635

**Comment by xfix** [comment]
For what it's worth, while I don't disagree that yanking can make it trickier to use an older version of Rust, xml5ever 0.16.0 and 0.16.1 have the exact same MSRV (1.36) - the same is the case with html5ever 0.25.0 and 0.25.1 (1.36). So it's not an issue for this particular yank.

(yes, I'm aware that those crates don't build with 1.36 currently, however, this is an issue with dependency that can be dealt by using `cargo update -p instant --precise 0.1.11`)

**Comment by untitaker** [comment]
I think it's fine in html5ever's case. I am not sure if the overall approach is viable for driving this feature forward.
