### ISSUE TITLE
Please release a new version of rcdom

### ISSUE THREAD

**Issue by notriddle** [servo/html5ever#470]
The html5ever and rcdom versions need to line up. As a result, [ammonia](https://github.com/rust-ammonia/ammonia/pull/156) is stuck with an outdated version.

**Comment by jdm** [comment]
rcdom is not a crate that is published anymore. It was never intended to be supported as a public dependency; ammonia should maintain its own fork as required

**Comment by notriddle** [comment]
Sure, I can do that, then.
