### ISSUE TITLE
the trait `TreeSink` is not implemented for `RcDom` with html5ever 0.26

### ISSUE THREAD

**Issue by b0bleet** [servo/html5ever#473]
Repro code:
```
let opts = ParseOpts {
    tree_builder: TreeBuilderOpts {
        drop_doctype: true,
        ..Default::default()
    },
    ..Default::default()
};
let rcdom_def = RcDom::default();
parse_document(rcdom_def, opts);
```
Error:
```
the trait `TreeSink` is not implemented for `RcDom`
```
But when I downgraded html5ever to 0.25 it worked well.

**Comment by jdm** [comment]
This happens because rcdom is not a crate that we publish anymore: https://github.com/servo/html5ever/tree/master/rcdom#readme . You can fork it if you want to continue using it.

**Comment by b0bleet** [comment]
I did try it with markup5ever_rcdom crate already.

**Comment by jdm** [comment]
The fork only works if it depends on the same html5ever/markup5ever crate versions.
