### ISSUE TITLE
html5ever README not getting published to crates.io

### ISSUE THREAD

**Issue by chriskrycho** [servo/html5ever#546]
Hey all, just what it says on the tin:

> html5ever v0.27.0 appears to have no `README.md` file

![CleanShot 2024-07-15 at 12 45 25@2x](https://github.com/user-attachments/assets/969585c1-5c00-438d-982c-68b9834268df)

Guessing this is just a quirk with however things are currently getting published automatically!

**Comment by nicoburns** [comment]
I think this is because the `html5ever` directory doesn't contain a `README.md` file. I think we can just stick `readme = "../README.md" in the `Cargo.toml` for `html5ever`, or we can of course create a separate README just for the html5ever crate.

**Comment by chriskrycho** [comment]
That's roughly what I was thinking as well, but being unfamiliar with the project didn’t want to just open a possibly-useless PR – so thanks!
