### ISSUE TITLE
Cargo version of markup5ever_rcdom has old dependencies

### ISSUE THREAD

**Issue by njaard** [servo/html5ever#550]
I think there was a glitch in the updating of markup5ever_rcdom

Right now, version 0.3.0 of `markup5ever_rcdom` depends on html5ever=0.27, markup5ever=0.12 and xml5ever=0.18

which are all one version back.

**Comment by jdm** [comment]
Please see https://github.com/servo/html5ever/issues/549.

**Comment by njaard** [comment]
I sent him an email
