### ISSUE TITLE
Possible bug: html5ever serializer is too aggressive on escaping special characters.

### ISSUE THREAD

**Issue by vnermolaev** [servo/html5ever#556]
Hi
The `html5ever::serialize` is too aggressive about escaping special characters, and it escapes them even in the `href` value of an a-tag.

Consider the html2html example with a hardcoded HTML:
```rust
use html5ever::driver::ParseOpts;
use html5ever::tendril::TendrilSink;
use html5ever::tree_builder::TreeBuilderOpts;
use html5ever::{parse_document, serialize};
use markup5ever_rcdom::{RcDom, SerializableHandle};
use std::io::{self, Cursor, Write};

fn main() {
    let opts = ParseOpts {
        tree_builder: TreeBuilderOpts {
            drop_doctype: true,
            ..Default::default()
        },
        ..Default::default()
    };

    let html = r#"</head><body><a href="https://link.com?a=1&b=2">test link</a></body></html>"#;

    let dom = parse_document(RcDom::default(), opts)
        .from_utf8()
        .read_from(&mut Cursor::new(html.as_bytes()))
        .unwrap();

    io::stdout()
        .write_all(b"<!DOCTYPE html>\n")
        .expect("writing DOCTYPE failed");
    let document: SerializableHandle = dom.document.clone().into();
    serialize(&mut io::stdout(), &document, Default::default()).expect("serialization failed");
}
```
The output is `<html><head></head><body><a href="https://link.com?a=1&amp;b=2">test link</a></body></html>
`, which is incorrect.

Am I missing something (such as a configuration option) or is this indeed a bug?

My dependencies:
```toml
[dependencies]
html5ever = "=0.27.0"
markup5ever_rcdom = "=0.3.0"
```

PS: @jdm I noticed you were interested in another `html2html` issue. I hope that's all right.

**Comment by jdm** [comment]
Definitely looks like a bug to me!

**Comment by jdm** [comment]
https://github.com/servo/html5ever/blob/main/html5ever/src/serialize/mod.rs#L160 is where the escaping is coming from, I presume.

**Comment by jdm** [comment]
The spec says we should be serializing attributes values using https://html.spec.whatwg.org/multipage/parsing.html#escapingString in attribute mode, which actually specifies that the & -> &am; replacement is expected. Fascinating!

**Comment by jdm** [comment]
This matches firefox's behaviour:
```
14:58:54.984 $ let e = document.createElement("a");
14:58:55.011 undefined
14:59:09.081 $ e.href = "https://example.com/foo?a=1&b=2"
14:59:09.092 "https://example.com/foo?a=1&b=2"
14:59:12.011 $ e.outerHTML
14:59:12.019 '<a href="https://example.com/foo?a=1&amp;b=2"></a>' 
```

**Comment by jdm** [comment]
Given that we match the specification and other browsers, I'm going to call this not a bug :)

**Comment by vnermolaev** [comment]
Haha, what a journey!
I just did follow the same rabbit hole and arrived ti the same conclusion.
However, it's great to have a confirmation! I appreciate this.
