### ISSUE TITLE
Is it possible to not spam `debug!` message

### ISSUE THREAD

**Issue by cdesouza-chromium** [servo/html5ever#561]
I've come across an issue where we get so many log messages from the tokeniser, that it disrupts our tests.  Like in places like this:

https://github.com/servo/html5ever/blob/main/html5ever/src/tokenizer/mod.rs#L280C17-L280C22

Is it possible to avoid spamming debug messages like this on top of other applications?

**Comment by mrobinson** [comment]
If you have trace logging turned on globally, it's pretty likely that your logs would be overwhelmed. The trace logging level is the most verbose type of logging and is generally only turned on per-component to use for in-depth debugging: https://docs.rs/log/latest/log/enum.Level.html#variant.Trace

**Comment by cdesouza-chromium** [comment]
I guess you're right. Thanks for the reply.
