### ISSUE TITLE
build errors with html5ever as cargo crate

### ISSUE THREAD

**Issue by ozten** [servo/html5ever#61]
rustc 0.13.0-nightly (6f4c11be3 2014-12-05 20:23:10 +0000)
cargo 0.0.1-pre-nightly (da789a6 2014-11-30 08:14:16 +0000)

Steps to Reproduce

    cargo new project --bin
    cd project

Add html5ever to `Cargo.toml`

    [dependencies.html5ever]
    git = "https://github.com/servo/html5ever"

Add html5ever to `main.rs`

    #![feature(phase)]

    extern crate html5ever;
    use html5ever::sink::common::{Document, Doctype, Text, Comment, Element};

Attempt build

	cargo build
	    Updating registry `https://github.com/rust-lang/crates.io-index`
	   Compiling html5ever_macros v0.0.0 (https://github.com/servo/html5ever#e7f74b65)
	   Compiling time v0.1.0
	   Compiling string_cache_macros v0.0.0 (https://github.com/servo/string-cache#40f25a17)
	/Users/ozten/.cargo/git/checkouts/html5ever-1ab8707684fb3258/master/macros/src/named_entities.rs:37:9: 37:21 error: unresolved enum variant, struct or const `Object`
	/Users/ozten/.cargo/git/checkouts/html5ever-1ab8707684fb3258/master/macros/src/named_entities.rs:37         json::Object(m) => m,
	                                                                                                            ^~~~~~~~~~~~
	error: aborting due to previous error
	   Compiling phf v0.2.0
	/Users/ozten/.cargo/git/checkouts/string-cache-628f0438d3df3ef7/master/macros/src/atom/mod.rs:18:25: 18:30 error: unresolved import `std::slice::Found`. There is no `Found` in `std::slice`
	/Users/ozten/.cargo/git/checkouts/string-cache-628f0438d3df3ef7/master/macros/src/atom/mod.rs:18 use std::slice::{Items, Found, NotFound};
	                                                                                                                         ^~~~~
	/Users/ozten/.cargo/git/checkouts/string-cache-628f0438d3df3ef7/master/macros/src/atom/mod.rs:18:32: 18:40 error: unresolved import `std::slice::NotFound`. There is no `NotFound` in `std::slice`
	/Users/ozten/.cargo/git/checkouts/string-cache-628f0438d3df3ef7/master/macros/src/atom/mod.rs:18 use std::slice::{Items, Found, NotFound};
	                                                                                                                                ^~~~~~~~
	error: aborting due to 2 previous errors
	Build failed, waiting for other jobs to finish...
	Could not compile `html5ever_macros`.

	To learn more, run the command again with --verbose.

I'm new to using cargo, so maybe I'm doing something wrong. The README states that this project tracks nightly Rust. Thanks for your help!

**Comment by kmcallister** [comment]
Yeah, we sometimes fall behind updating to the Rust nightlies.  I think that's what happened here.  Your build instructions work for me now :)
