### ISSUE TITLE
Fix scripts/bench-branches.py

### ISSUE THREAD

**Issue by kmcallister** [servo/html5ever#72]
It uses the removed libtest `--save-metrics` feature. See 22a97c2f38a253728ef975d2330d964f524f8134 and rust-lang/rust#19145.

**Comment by Ygg01** [comment]
We removed this one with #268 I'm assuming it's no longer relevant.

**Comment by SimonSapin** [comment]
Let’s close, it’s in git history if we want to fix it and use it again later.
