### ISSUE TITLE
Build libhtml5ever_for_c.a via cargo

### ISSUE THREAD

**Issue by aroben** [servo/html5ever#95]
`libhtml5ever_for_c.a` is the only target that requires `Makefile.in`. Everything else can be built via `cargo`. It would be great to use `cargo` to build `libhtml5ever_for_c.a` too; then we could get rid of the Makefile entirely.

**Comment by kmcallister** [comment]
Maybe the C bindings should become a separate crate in the same repo. Does Cargo support `staticlib` crates?

I'm not sure there's any need to build html5ever itself specially for C consumers, now that the Rust runtime is gone.

**Comment by steveklabnik** [comment]
> Does Cargo support staticlib crates?

Yes, it does. http://doc.crates.io/manifest.html#building-dynamic-or-static-libraries

**Comment by kmcallister** [comment]
This is [working well for tendril](https://github.com/kmcallister/tendril/tree/master/capi).
