### ISSUE TITLE
TreeBuilder.quirks_mode should be initialized to match quirks mode of the sink's document

### ISSUE THREAD

**Issue by ChrisParis** [servo/html5ever#96]

**Comment by ChrisParis** [comment]
We could add a quirks_mode() getter to the TreeSink trait, which would let the parser pull the quirks mode from the sink. Or we could add a quirks_mode to TreeBuilderOpts, which would let the client supply the initial value. Preference? Or a different approach?

**Comment by kmcallister** [comment]
Let's add it to `TreeBuilderOpts`.
